import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, padding: 16, gap: 8 },
  title: { fontSize: 20, fontWeight: "700" },
  description: { opacity: 0.75 },

  scrollContent: { paddingBottom: 24 },

  stack: { gap: 12 },
  row: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  rowItem: { flexGrow: 1, minWidth: 220 },

  section: { borderWidth: 1, borderRadius: 12, padding: 12, borderColor: "#ddd" },
  sectionTitle: { fontSize: 16, fontWeight: "700", marginBottom: 8 },
  sectionBody: { gap: 12 },

  field: { gap: 6 },
  label: { fontWeight: "600" },
  errorText: { color: "#b00020" },

  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inputError: { borderColor: "#b00020" },

  inlineRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },

  select: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    overflow: "hidden",
  },
  picker: { height: 44 },

  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  chipActive: { borderColor: "#111" },
  chipText: { fontSize: 13 },

  footer: { flexDirection: "row", gap: 12 },
  buttonPrimary: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: "#111",
  },
  buttonSecondary: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#111",
    backgroundColor: "#fff",
  },
  buttonText: { color: "#fff", fontWeight: "700" },
  buttonSecondaryText: { color: "#111", fontWeight: "700" },
  buttonDisabled: { opacity: 0.5 },

  signatureBox: { borderWidth: 1, borderColor: "#ddd", borderRadius: 10, overflow: "hidden" },
  signatureFooter: { flexDirection: "row", alignItems: "center", gap: 12, padding: 8 },
  signatureHint: { opacity: 0.7 },
  signatureFallback: { paddingVertical: 8 },
  signatureField: { gap: 8 },
  signaturePreviewFrame: {
    width: "100%",
    height: 120,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#fff",
    padding: 8,
  },
  signaturePreview: {
    width: "100%",
    height: "100%",
  },
  signatureEmptyFrame: {
    width: "100%",
    height: 72,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 12,
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
  },
  signatureClearBtn: {
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#111",
    backgroundColor: "#fff",
  },
  signatureModal: { flex: 1, backgroundColor: "#fff" },
  signatureModalHeader: { paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderColor: "#eee" },
  signatureModalTitle: { fontSize: 18, fontWeight: "700" },
  signatureCanvasFrame: { flex: 1, margin: 16, borderWidth: 1, borderColor: "#ddd", borderRadius: 12, overflow: "hidden" },
  signatureModalActions: { flexDirection: "row", gap: 12, padding: 16, borderTopWidth: 1, borderColor: "#eee" },
  signatureCancelBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#111",
    backgroundColor: "#fff",
  },
  signatureDialogClearBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#111",
    backgroundColor: "#fff",
  },
  signatureDoneBtn: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: "#111",
  },

  imageField: { gap: 8 },
  menuCard: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 12,
    backgroundColor: "#fff",
    padding: 6,
    gap: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  menuItem: {
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  menuItemText: { color: "#111", fontWeight: "600" },
  inputDisabled: { backgroundColor: "#f8fafc", color: "#667085" },
  imagePreviewFrame: {
    width: "100%",
    aspectRatio: 4 / 3,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#f8fafc",
  },
  imagePreview: {
    width: "100%",
    height: "100%",
  },

  fileHint: { marginTop: 6, opacity: 0.7 },
});
